coverage:
  status:
    patch:
      default:
        target: 100%
    project:
      default:
        target: 95%

comment:
  layout: "header,reach, diff, flags, files"
  behavior: default
  require_changes: false
